import { Shield, Mail, Calendar, MapPin } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <main className='min-h-screen bg-background'>
      {/* Header */}
      <header className='border-b border-border bg-card'>
        <div className='mx-auto max-w-4xl px-6 py-8'>
          <div className='flex items-center gap-3'>
            <div className='flex h-10 w-10 items-center justify-center rounded-lg bg-primary'>
              <Shield className='h-5 w-5 text-primary-foreground' />
            </div>
            <div>
              <h1 className='text-2xl font-bold text-foreground'>Praywrite</h1>
              <p className='text-sm text-muted-foreground'>Privacy Policy</p>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <article className='mx-auto max-w-4xl px-6 py-12'>
        {/* Last Updated */}
        <div className='mb-8 flex items-center gap-2 text-sm text-muted-foreground'>
          <Calendar className='h-4 w-4' />
          <span>Last updated: December 15, 2025</span>
        </div>

        {/* Introduction */}
        <section className='mb-12'>
          <p className='text-lg leading-relaxed text-foreground'>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className='mt-4 leading-relaxed text-muted-foreground'>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        {/* Interpretation and Definitions */}
        <Section title='Interpretation and Definitions'>
          <Subsection title='Interpretation'>
            <p>
              The words whose initial letters are capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </Subsection>

          <Subsection title='Definitions'>
            <p className='mb-4'>For the purposes of this Privacy Policy:</p>
            <DefinitionList
              definitions={[
                {
                  term: "Account",
                  definition:
                    "means a unique account created for You to access our Service or parts of our Service.",
                },
                {
                  term: "Affiliate",
                  definition:
                    'means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                },
                {
                  term: "Application",
                  definition:
                    "refers to Praywrite, the software program provided by the Company.",
                },
                {
                  term: "Company",
                  definition:
                    '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Praywrite.',
                },
                { term: "Country", definition: "refers to: Czechia" },
                {
                  term: "Device",
                  definition:
                    "means any device that can access the Service such as a computer, a cell phone or a digital tablet.",
                },
                {
                  term: "Personal Data",
                  definition:
                    "is any information that relates to an identified or identifiable individual.",
                },
                { term: "Service", definition: "refers to the Application." },
                {
                  term: "Service Provider",
                  definition:
                    "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
                },
                {
                  term: "Usage Data",
                  definition:
                    "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
                },
                {
                  term: "You",
                  definition:
                    "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
                },
              ]}
            />
          </Subsection>
        </Section>

        {/* Collecting and Using Your Personal Data */}
        <Section title='Collecting and Using Your Personal Data'>
          <Subsection title='Types of Data Collected'>
            <h4 className='mb-3 font-semibold text-foreground'>
              Personal Data
            </h4>
            <p className='mb-4'>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className='mb-6 list-inside list-disc space-y-2 text-muted-foreground'>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>

            <h4 className='mb-3 font-semibold text-foreground'>Usage Data</h4>
            <p className='mb-4'>
              Usage Data is collected automatically when using the Service.
            </p>
            <p className='mb-4'>
              Usage Data may include information such as Your Device&apos;s
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile
              device&apos;s unique ID, the IP address of Your mobile device,
              Your mobile operating system, the type of mobile Internet browser
              You use, unique device identifiers and other diagnostic data.
            </p>
          </Subsection>

          <Subsection title='Use of Your Personal Data'>
            <p className='mb-4'>
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className='list-inside list-disc space-y-3 text-muted-foreground'>
              <li>
                <strong className='text-foreground'>
                  To provide and maintain our Service
                </strong>
                , including to monitor the usage of our Service.
              </li>
              <li>
                <strong className='text-foreground'>
                  To manage Your Account:
                </strong>{" "}
                to manage Your registration as a user of the Service.
              </li>
              <li>
                <strong className='text-foreground'>
                  For the performance of a contract:
                </strong>{" "}
                the development, compliance and undertaking of the purchase
                contract for the products, items or services You have purchased.
              </li>
              <li>
                <strong className='text-foreground'>To contact You:</strong> To
                contact You by email, telephone calls, SMS, or other equivalent
                forms of electronic communication.
              </li>
              <li>
                <strong className='text-foreground'>To provide You</strong> with
                news, special offers, and general information about other goods,
                services and events which We offer.
              </li>
              <li>
                <strong className='text-foreground'>
                  To manage Your requests:
                </strong>{" "}
                To attend and manage Your requests to Us.
              </li>
              <li>
                <strong className='text-foreground'>
                  For business transfers:
                </strong>{" "}
                We may use Your information to evaluate or conduct a merger,
                divestiture, restructuring, reorganization, dissolution, or
                other sale or transfer of some or all of Our assets.
              </li>
              <li>
                <strong className='text-foreground'>For other purposes:</strong>{" "}
                We may use Your information for data analysis, identifying usage
                trends, and to evaluate and improve our Service.
              </li>
            </ul>
          </Subsection>

          <Subsection title='Sharing Your Personal Information'>
            <p className='mb-4'>
              We may share Your personal information in the following
              situations:
            </p>
            <ul className='list-inside list-disc space-y-3 text-muted-foreground'>
              <li>
                <strong className='text-foreground'>
                  With Service Providers:
                </strong>{" "}
                We may share Your personal information with Service Providers to
                monitor and analyze the use of our Service.
              </li>
              <li>
                <strong className='text-foreground'>
                  For business transfers:
                </strong>{" "}
                We may share or transfer Your personal information in connection
                with any merger, sale of Company assets, financing, or
                acquisition.
              </li>
              <li>
                <strong className='text-foreground'>With Affiliates:</strong> We
                may share Your information with Our affiliates, in which case we
                will require those affiliates to honor this Privacy Policy.
              </li>
              <li>
                <strong className='text-foreground'>
                  With business partners:
                </strong>{" "}
                We may share Your information with Our business partners to
                offer You certain products, services or promotions.
              </li>
              <li>
                <strong className='text-foreground'>With other users:</strong>{" "}
                when You share personal information or otherwise interact in the
                public areas with other users.
              </li>
              <li>
                <strong className='text-foreground'>With Your consent:</strong>{" "}
                We may disclose Your personal information for any other purpose
                with Your consent.
              </li>
            </ul>
          </Subsection>
        </Section>

        {/* Retention of Your Personal Data */}
        <Section title='Retention of Your Personal Data'>
          <p className='mb-4'>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
          <p>
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service.
          </p>
        </Section>

        {/* Transfer of Your Personal Data */}
        <Section title='Transfer of Your Personal Data'>
          <p className='mb-4'>
            Your information, including Personal Data, is processed at the
            Company&apos;s operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            from those from Your jurisdiction.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place.
          </p>
        </Section>

        {/* Delete Your Personal Data */}
        <Section title='Delete Your Personal Data'>
          <p className='mb-4'>
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about You.
          </p>
          <p className='mb-4'>
            Our Service may give You the ability to delete certain information
            about You from within the Service. You may update, amend, or delete
            Your information at any time by signing in to Your Account, if you
            have one, and visiting the account settings section that allows you
            to manage Your personal information.
          </p>
          <p>
            Please note, however, that We may need to retain certain information
            when we have a legal obligation or lawful basis to do so.
          </p>
        </Section>

        {/* Disclosure of Your Personal Data */}
        <Section title='Disclosure of Your Personal Data'>
          <Subsection title='Business Transactions'>
            <p>
              If the Company is involved in a merger, acquisition or asset sale,
              Your Personal Data may be transferred. We will provide notice
              before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
            </p>
          </Subsection>

          <Subsection title='Law Enforcement'>
            <p>
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </p>
          </Subsection>

          <Subsection title='Other Legal Requirements'>
            <p className='mb-4'>
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul className='list-inside list-disc space-y-2 text-muted-foreground'>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>
          </Subsection>
        </Section>

        {/* Security */}
        <Section title='Security of Your Personal Data'>
          <p>
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially reasonable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
        </Section>

        {/* Children's Privacy */}
        <Section title="Children's Privacy">
          <p className='mb-4'>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us.
          </p>
          <p>
            If We become aware that We have collected Personal Data from anyone
            under the age of 13 without verification of parental consent, We
            take steps to remove that information from Our servers.
          </p>
        </Section>

        {/* Links to Other Websites */}
        <Section title='Links to Other Websites'>
          <p className='mb-4'>
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party&apos;s site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </Section>

        {/* Changes */}
        <Section title='Changes to this Privacy Policy'>
          <p className='mb-4'>
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the
            &quot;Last updated&quot; date at the top of this Privacy Policy.
          </p>
        </Section>

        {/* Contact Us */}
        <Section title='Contact Us'>
          <p className='mb-4'>
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <div className='flex items-center gap-3 rounded-lg border border-border bg-card p-4'>
            <Mail className='h-5 w-5 text-muted-foreground' />
            <a
              href='mailto:okpoka92@gmail.com'
              className='text-foreground hover:underline'
            >
              okpoka92@gmail.com
            </a>
          </div>
        </Section>

        {/* Footer */}
        <footer className='mt-16 border-t border-border pt-8'>
          <div className='flex items-center gap-2 text-sm text-muted-foreground'>
            <MapPin className='h-4 w-4' />
            <span>Czechia</span>
          </div>
        </footer>
      </article>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className='mb-12'>
      <h2 className='mb-6 text-2xl font-bold text-foreground'>{title}</h2>
      <div className='space-y-4 leading-relaxed text-muted-foreground'>
        {children}
      </div>
    </section>
  );
}

function Subsection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className='mb-6'>
      <h3 className='mb-3 text-lg font-semibold text-foreground'>{title}</h3>
      <div className='space-y-3'>{children}</div>
    </div>
  );
}

function DefinitionList({
  definitions,
}: {
  definitions: { term: string; definition: string }[];
}) {
  return (
    <dl className='space-y-4'>
      {definitions.map((item) => (
        <div
          key={item.term}
          className='rounded-lg border border-border bg-card/50 p-4'
        >
          <dt className='font-semibold text-foreground'>{item.term}</dt>
          <dd className='mt-1 text-muted-foreground'>{item.definition}</dd>
        </div>
      ))}
    </dl>
  );
}
